name: "Trivy Plan Scan"
description: "Scans Terraform plan output with Trivy (all severities, fail on any)"

inputs:
  tfplan-path:
    default: "tfplan"
    required: false

runs:
  using: "composite"
  steps:
    - name: Trivy Plan Scan
      id: trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        scan-ref: ${{ inputs.tfplan-path }}
        format: json
        output: trivy-plan.json
        severity: CRITICAL,HIGH,MEDIUM,LOW
        exit-code: '1'                 # fail on *any* finding
        cache-dir: .trivy-cache

    - name: Count HIGH+CRITICAL
      id: count
      if: always()
      run: |
        CNT=$(jq -r '
          .Results[].Vulnerabilities // [] |
          map(select(.Severity == "CRITICAL" or .Severity == "HIGH")) |
          length
        ' trivy-plan.json 2>/dev/null || echo 0)
        echo "high_critical=$CNT" >> $GITHUB_OUTPUT
      shell: bash

    - name: Count ALL
      id: total
      if: always()
      run: |
        TOTAL=$(jq -r '
          .Results[].Vulnerabilities // [] |
          length
        ' trivy-plan.json 2>/dev/null || echo 0)
        echo "total=$TOTAL" >> $GITHUB_OUTPUT
      shell: bash

    - name: Upload plan results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trivy-plan-${{ github.run_id }}
        path: trivy-plan.json
        retention-days: 30