name: "Trivy Plan Scan"
description: "Scans Terraform plan output with Trivy"
inputs:
  tfplan-path:
    default: "tfplan"
    required: false
  severity:
    default: "CRITICAL,HIGH"
    required: false

runs:
  using: "composite"
  steps:
    - name: Trivy Plan Scan
      uses: aquasecurity/trivy-action@v0.33.1
      with:
        scan-type: 'config'
        scan-ref: ${{ inputs.tfplan-path }}
        format: 'sarif'
        output: 'trivy-plan.sarif'
        severity: ${{ inputs.severity }}
        cache-ttl: '24h'

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-plan.sarif