name: "Trivy Static Scan"
description: "Scans Terraform source files (.tf, .tfvars) with Trivy"
inputs:
  path:
    default: "."
    required: false
  severity:
    default: "CRITICAL,HIGH"
    required: false

runs:
  using: "composite"
  steps:
    - name: Trivy Static Scan
      uses: aquasecurity/trivy-action@v0.33.1
      with:
        scan-type: 'fs'
        scan-ref: ${{ inputs.path }}
        format: 'sarif'
        output: 'trivy-static.sarif'
        severity: ${{ inputs.severity }}
        cache-ttl: '24h'

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-static.sarif