# .github/actions/trivy-static-scan/action.yml
name: "Trivy Static Scan"
description: "Scans Terraform source files (.tf, .tfvars) with Trivy"
inputs:
  path:
    default: "."
    required: false
  severity:
    default: "CRITICAL,HIGH"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trivy Static Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: ${{ inputs.path }}
        format: 'sarif'
        output: 'trivy-static.sarif'
        severity: ${{ inputs.severity }}
        cache-dir: .trivy-cache  #optional

    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-static.sarif

  #       #sji continue-on-error: true not suitable long term - maybe send alerts to something like this: 
  #   - name: Notify Rocket.Chat
  #     if failure()  # only send on failure, remove this line to always send
  #     run: |
  #       curl -X POST -H 'Content-Type: application/json' \
  #         -d '{
  #               "text": "🚨 GitHub Action failed: {{ github.workflow }} > {{ github.job }}\nCommit: {{ github.sha }}\n<{{ github.server_url }}/{{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
  #             }' \
  #         {{ secrets.ROCKETCHAT_WEBHOOK_URL }}
  # # only on scans of main branch