name: tflint
description: Run TFLint

runs:
  using: "composite"

  steps:
  - name: Terraform FMT
    run: terraform fmt -check -recursive
    shell: bash

  - name: Cache plugin dir
    uses: actions/cache@v4      
    with:
      path: ~/.tflint.d/plugins
      key: tflint-plugins-${{ runner.os }}-${{ hashFiles('.tflint.hcl') }}
      restore-keys: |
        tflint-plugins-${{ runner.os }}-

  - name: Setup TFLint
    uses: terraform-linters/setup-tflint@v4      
    with:
      tflint_version: latest

  - name: Show version
    run: tflint --version
    shell: bash

  - name: Init TFLint
    run: tflint --init
    shell: bash

  - name: Run TFLint
    run: tflint -f compact
    shell: bash