name: Terraform Destroy
description: Destroys terraform

inputs:
  environment:
    required: true
  tfvars-file:
    required: true
  backend-file-path:
    required: true
  auto-apply:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # ---------------------------------------------
    # 1. Get Terraform Version
    # ---------------------------------------------
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # ---------------------------------------------
    # 2. Setup Terraform
    # ---------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: ${{ steps.tf-version.outputs.version }}
  
    # ---------------------------------------------
    # 3. Terraform Init - Get env backend
    # ---------------------------------------------
    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        ls -la
        echo "Initializing Terraform with backend: ${{ inputs.backend-file-path }}"
        terraform init -upgrade -backend-config="${{ inputs.backend-file-path }}"
        terraform providers

 # TEMP! releases lock file for tfstate fuck ups
    # #find in console/dynamodb/lock table/Explore table items (top right)
    - name: Release stale lock (works every time)
      shell: bash
      run: |
        echo "Forcing unlock of any stale lock – safe if none exists"
        terraform force-unlock -force f0021d2f-ae21-a931-d920-6e69965c6ea0 || true
      continue-on-error: true
    # Destroy
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var-file=${{ inputs.tfvars-file }}
      shell: bash