name: Terraform Destroy
description: Destroys terraform

inputs:
  environment:
    required: true
  tfvars-file:
    required: true
  backend-file-path:
    required: true
  auto-apply:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # ---------------------------------------------
    # Terraform Version
    # ---------------------------------------------
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # ---------------------------------------------
    # Setup Terraform
    # ---------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: ${{ steps.tf-version.outputs.version }}
  
    # ---------------------------------------------
    # Terraform Init (Using Env backend)
    # ---------------------------------------------
    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        ls -la
        echo "Initializing Terraform with backend: ${{ inputs.backend-file-path }}"
        terraform init -upgrade -backend-config="${{ inputs.backend-file-path }}"
        terraform providers

    # # ---------------------------------------------
    # # Terraform Destroy
    # # ---------------------------------------------
    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve -var-file=${{ inputs.tfvars-file }}
    #   shell: bash

    # KMS cleanup
    - name: Delete lingering KMS alias
      run: aws kms delete-alias --alias-name alias/eks/catalina-dev || true

    - name: Purge old KMS key (if in Pending Deletion)
      run: |
        KEY_ID=$(aws kms list-keys --query "Keys[?contains(KeyArn,'catalina-dev')].KeyId" --output text)
        for id in $KEY_ID; do
          echo "Scheduling immediate deletion of old key $id"
          aws kms schedule-key-deletion --key-id $id --pending-window-in-days 7
          aws kms cancel-key-deletion --key-id $id || true
        done