name: Terraform Destroy
description: Destroys terraform

inputs:
  environment:
    required: true
  tfvars-file:
    required: true
  backend-file-path:
    required: true
  auto-apply:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # ---------------------------------------------
    # Terraform Version
    # ---------------------------------------------
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # ---------------------------------------------
    # Setup Terraform
    # ---------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: ${{ steps.tf-version.outputs.version }}
  
    # ---------------------------------------------
    # Terraform Init (Using Env backend)
    # ---------------------------------------------
    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        ls -la
        echo "Initializing Terraform with backend: ${{ inputs.backend-file-path }}"
        terraform init -upgrade -backend-config="${{ inputs.backend-file-path }}"
        terraform providers

    # # ---------------------------------------------
    # # Terraform Destroy
    # # ---------------------------------------------
    # - name: Terraform Destroy
    #   run: terraform destroy -auto-approve -var-file=${{ inputs.tfvars-file }}
    #   shell: bash

    # ---------------------------------------------
    # KMS cleanup
    # ---------------------------------------------
    - name: Clean up old KMS alias + key (any region)
      shell: bash
      run: |
        REGION="eu-north-1"
        echo "Using region: $REGION"
        
        # 1. Delete the alias (instant, idempotent)
        echo "Deleting KMS alias if it exists..."
        aws kms delete-alias --region "$REGION" --alias-name alias/eks/catalina-dev || true

        # 2. Find and cancel any pending-deletion key that contains catalina-dev in its description/ARN
        echo "Looking for leftover catalina-dev KMS keys..."
        KEY_IDS=$(aws kms list-keys --region "$REGION" --query "Keys[].KeyId" --output text)

        for id in $KEY_IDS; do
          # loop over every key in the account
          ARN=$(aws kms describe-key --region "$REGION" --key-id "$id" --query 'KeyMetadata.KeyArn' --output text)
          DESC=$(aws kms describe-key --region "$REGION" --key-id "$id" --query 'KeyMetadata.Description' --output text || echo "")

          if [[ "$ARN" == *"catalina-dev"* ]] || [[ "$DESC" == *"catalina-dev"* ]]; then
            echo "Found leftover key $id – cancelling pending deletion (if any) and re-enabling"
            aws kms cancel-key-deletion --region "$REGION" --key-id "$id" --no-cli-pager || true
            aws kms enable-key         --region "$REGION" --key-id "$id" --no-cli-pager || true
          fi
        done

        echo "KMS cleanup complete"     