name: Terraform Destroy
description: Destroys terraform

inputs:
  environment:
    required: true
  tfvars-file:
    required: true
  backend-file-path:
    required: true
  auto-apply:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # ---------------------------------------------
    # Terraform Version
    # ---------------------------------------------
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # ---------------------------------------------
    # Setup Terraform
    # ---------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: ${{ steps.tf-version.outputs.version }}
  
    # ---------------------------------------------
    # Terraform Init (Using Env backend)
    # ---------------------------------------------
    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        ls -la
        echo "Initializing Terraform with backend: ${{ inputs.backend-file-path }}"
        terraform init -upgrade -backend-config="${{ inputs.backend-file-path }}"
        terraform providers

    # ---------------------------------------------
    # Terraform Destroy
    # ---------------------------------------------
    - name: Terraform Destroy
      if: ${{ inputs.auto-apply == 'true' }}
      run: terraform destroy -auto-approve -var-file=${{ inputs.tfvars-file }}
      shell: bash