name: Terraform Destroy
description: Destroys terraform

inputs:
  environment:
    required: true
  tfvars-file:
    required: true
  backend-file-path:
    required: true
  auto-apply:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    # ---------------------------------------------
    # 1. Get Terraform Version
    # ---------------------------------------------
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # ---------------------------------------------
    # 2. Setup Terraform
    # ---------------------------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: ${{ steps.tf-version.outputs.version }}
        
    # ---------------------------------------------
    # 4. Terraform Init - Get env backend
    # ---------------------------------------------
    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        if [ -z "backend.hcl" ]; then
          echo "ERROR: backend-file-path is missing!"
          exit 1
        fi

        terraform init

    # Apply
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var-file=dev.tfvars
      shell: bash
      #working-directory: ./environments/${{ steps.set-env.outputs.environment }}
    - name: Terraform Apply
      shell: bash
      if: ${{ inputs.auto-apply }}
      run: terraform apply -auto-approve tfplan