name: "Terraform Security Scan (All)"
description: "Trivy static + plan scan with SARIF, artifacts & alerts"

inputs:
  tfvars-file:
    required: true
  environment:
    required: true
  backend-file-path:
    required: true
    default: 'backend.hcl'
  auto-apply:
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        cat ${{ inputs.backend-file-path }}
        if [ -z ${{ inputs.backend-file-path }} ]; then
          echo "ERROR: backend file is missing!"
          echo ${{ inputs.backend-file-path }}
          exit 1
        fi
        terraform init -upgrade -backend-config="${{ inputs.backend-file-path }}"
        terraform providers

    # ========================
    # Static Trivy Scan
    # ========================
    - name: Trivy Static Scan - Pretty
      id: static
      continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        format: table
        severity: CRITICAL,HIGH,MEDIUM,LOW
        exit-code: '1'

    - name: Trivy Static Scan - SARIF
      if: always()
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        format: sarif
        output: trivy-static.sarif
        severity: CRITICAL,HIGH,MEDIUM,LOW

    # ========================
    # Terraform Plan → JSON
    # ========================
    - name: Terraform Plan (JSON)
      shell: bash
      run: |
        terraform plan -var-file="${{ inputs.tfvars-file }}" -out=tfplan
        terraform show -json tfplan > tfplan.json

    # ==========================
    # Plan Trivy Scan (Dynamic)
    # ==========================
    - name: Trivy Plan Scan - Pretty
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        input: tfplan.json
        format: table
        severity: CRITICAL,HIGH,MEDIUM,LOW
        exit-code: '1'

    - name: Trivy Plan Scan - SARIF
      if: always()
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        input: tfplan.json
        format: sarif
        output: trivy-plan.sarif
        severity: CRITICAL,HIGH,MEDIUM,LOW

    # # Upload SARIF to GitHub Security tab 'sji can I? think this is paid
    # - name: Upload SARIF
    #   if: always()
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: |
    #       trivy-static.sarif
    #       trivy-plan.sarif

    # ========================
    # Artifact Upload
    # ========================
    - name: Upload Scan Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: terraform-security-scan-${{ github.run_number }}-${{ inputs.environment }}
        path: |
          trivy-static.sarif
          trivy-plan.sarif
          tfplan.json
          backend.hcl
        retention-days: 90
        if-no-files-found: warn