name: "Terraform Security Scan (All)"
description: "Runs Trivy (static + plan)"
inputs:
  tfvars-file:
    required: true
  environment:
    required: true
  backend-file-path:
    required: true
    default: 'backend.hcl'

runs:
  using: "composite"
  steps:
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: ${{ steps.tf-version.outputs.version }}

    - name: Terraform Init
      shell: bash
      run: |
        set -euo pipefail
        if [ -z "backend.hcl" ]; then
          echo "ERROR: backend-file-path is missing!"
          exit 1
        fi

        terraform init

    # Static scans
    - uses: ./.github/actions/security/trivy-static

    # Plan + dynamic scan
    - name: Terraform Plan
      id: plan
      shell: bash
      run: |
        terraform plan \
          -var-file="${{ inputs.tfvars-file }}" \
          -json > tfplan.json

    - uses: ./.github/actions/security/trivy-plan