name: "Terraform Security Scan (All)"
description: "Runs Trivy static + plan scan"

inputs:
  tfvars-file:
    required: true
  environment:
    required: true
  backend-file-path:
    required: true
    default: 'backend.hcl'
  auto-apply:
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init with Backend
      shell: bash
      run: |
        set -euo pipefail
        if [ ! -f "${{ inputs.backend-file-path }}" ]; then
          echo "Backend file not found: ${{ inputs.backend-file-path }}" >&2
          exit 1
        fi
        terraform init -backend-config="${{ inputs.backend-file-path }}"

    # Static Scan (replaces tfsec)
    - name: Trivy Static Scan - Pretty Output
      id: static
      continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        format: table
        severity: CRITICAL,HIGH,MEDIUM,LOW
        exit-code: '1'

    - name: Trivy Static Scan - SARIF
      if: always()
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: config
        format: sarif
        output: trivy-static.sarif
        severity: CRITICAL,HIGH,MEDIUM,LOW

    # Plan
    - name: Terraform Plan (JSON)
      shell: bash
      run: |
        set -euo pipefail
        terraform plan -var-file="${{ inputs.tfvars-file }}" -json > tfplan.json

    # Plan Scan
    - name: Trivy Plan Scan - Pretty Output
      id: plan
      continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: terraformplan
        scan-ref: tfplan.json
        format: table
        severity: CRITICAL,HIGH,MEDIUM,LOW
        exit-code: '1'

    - name: Trivy Plan Scan - SARIF
      if: always()
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: terraformplan
        scan-ref: tfplan.json
        format: sarif
        output: trivy-plan.sarif
        severity: CRITICAL,HIGH,MEDIUM,LOW

    # Upload to GitHub Security tab
    - name: Upload SARIF to Code Scanning
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: |
          trivy-static.sarif
          trivy-plan.sarif

    # Optional auto-apply
    - name: Terraform Apply (if requested)
      if: inputs.auto-apply == 'true'
      shell: bash
      run: terraform apply -auto-approve -input=false

#Go to your repo → Settings → Secrets and variables → Actions
# Add a new secret:
# Name: ROCKET_CHAT_WEBHOOK
# Value: Your Rocket.Chat incoming webhook URL (e.g. https://chat.yourcompany.com/hooks/xxxxxxxxxxxxxxxxx)
    # ── Rocket.Chat Alert on Failure ──────────────────────────────────
    # - name: Send Rocket.Chat Alert on Failure
    #   if: failure() || steps.static-table.outcome == 'failure' || steps.plan-table.outcome == 'failure'
    #   env:
    #     ROCKET_CHAT_WEBHOOK: ${{ secrets.ROCKET_CHAT_WEBHOOK }}   # Put your webhook URL in Secrets
    #   run: |
    #     RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    #     BRANCH="${{ github.ref_name }}"
    #     ENV="${{ inputs.environment || 'dev' }}"

    #     curl -X POST "$ROCKET_CHAT_WEBHOOK" \
    #       -H "Content-Type: application/json" \
    #       -d '{
    #         "text": "Terraform Security Scan FAILED",
    #         "attachments": [
    #           {
    #             "title": "Security issues found in Terraform code",
    #             "title_link": "'"$RUN_URL"'",
    #             "color": "#B22222",
    #             "fields": [
    #               { "title": "Repository", "value": "${{ github.repository }}", "short": true },
    #               { "title": "Branch", "value": "'"$BRANCH"'", "short": true },
    #               { "title": "Environment", "value": "'"$ENV"'", "short": true },
    #               { "title": "Triggered by", "value": "${{ github.actor }}", "short": true }
    #             ],
    #             "footer": "GitHub Actions • Terraform + Trivy",
    #             "ts": '"$(date +%s)"'
    #           }
    #         ]
    #       }'