name: "Trivy Static Scan"
description: "Scans Terraform source files with Trivy (all severities, fail on any)"

runs:
  using: "composite"
  steps:
    - name: Trivy Static Scan
      id: trivy
      continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: '.'
        format: json
        output: trivy-static.json
        severity: CRITICAL,HIGH,MEDIUM,LOW
        exit-code: '1'                 # fail on *any* finding
        cache-dir: .trivy-cache

    - name: Count HIGH+CRITICAL
      id: count
      if: always()
      run: |
        CNT=$(jq -r '
          .Results[].Vulnerabilities // [] |
          map(select(.Severity == "CRITICAL" or .Severity == "HIGH")) |
          length
        ' trivy-static.json 2>/dev/null || echo 0)
        echo "high_critical=$CNT" >> $GITHUB_OUTPUT
      shell: bash

    - name: Count ALL
      id: total
      if: always()
      run: |
        TOTAL=$(jq -r '
          .Results[].Vulnerabilities // [] |
          length
        ' trivy-static.json 2>/dev/null || echo 0)
        echo "total=$TOTAL" >> $GITHUB_OUTPUT
      shell: bash

    - name: Upload static results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trivy-static-${{ github.run_id }}-${{ github.job }}
        path: trivy-static.json
        retention-days: 30