name: 'Terraform Version'
description: 'Read the Terraform version from .terraform-version file'

inputs:
  working-directory:
    description: 'The directory where the .terraform-version file is located'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    - name: Read Terraform Version
      shell: bash
      id: tf-version
      run: |
        ls -la
        pwd
        if [ ! -f .terraform-version ]; then
          echo "Error: .terraform-version file not found."
          exit 1
        fi
        version=$(cat .terraform-version)
        echo "Terraform version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}